Add slime and mage
Leminode/the-last-hero pull request #7
Opened 2024-10-29 18:21 UTC by Simukas1

2024-10-29 18:55 UTC, epuluikis requested changes

2024-10-29 18:55 UTC, epuluikis commented on ProjectSettings/ProjectVersion.txt
> +m_EditorVersionWithRevision: 2022.3.47f1 (88c277b85d21)
pasiupdatink savo editor ir nedowngradink projekto

2024-10-29 18:55 UTC, epuluikis commented on ProjectSettings/TagManager.asset.orig
> +>>>>>>> Stashed changes
likuciai nuo merge conflict

2024-10-29 19:50 UTC, Simukas1 commented on ProjectSettings/TagManager.asset.orig
> +>>>>>>> Stashed changes
Oops

2024-10-30 19:24 UTC, epuluikis approved these changes

2024-10-30 19:25 UTC, merged